export const PERMISSIONS = {
  SYSTEM_ADMIN: ['DASHBOARD_VIEW','USER_VIEW','USER_CREATE','USER_UPDATE','USER_DELETE','USER_ROLE_UPDATE','AUDIT_VIEW','SYSTEM_SETTINGS_VIEW','SYSTEM_SETTINGS_UPDATE'],
  ADMIN: ['DASHBOARD_VIEW','USER_VIEW','USER_CREATE','USER_UPDATE','USER_DELETE','USER_ROLE_UPDATE','AUDIT_VIEW','SYSTEM_SETTINGS_VIEW','SYSTEM_SETTINGS_UPDATE'],
  FINANCE_MANAGER: ['DASHBOARD_VIEW','TRANSACTION_VIEW','TRANSACTION_CREATE','TRANSACTION_UPDATE','INVOICE_VIEW','INVOICE_UPLOAD','INVOICE_PROCESS','INVOICE_UPDATE','INVOICE_APPROVE','INVOICE_REJECT','INVOICE_PAYMENT','VENDOR_VIEW','VENDOR_CREATE','VENDOR_UPDATE','ANOMALY_VIEW','ANOMALY_ANALYZE','FORECAST_VIEW','FORECAST_GENERATE','BUDGET_VIEW','BUDGET_CREATE','BUDGET_UPDATE','BUDGET_APPROVE','RISK_VIEW','ASSISTANT_USE','APPROVAL_VIEW','APPROVAL_APPROVE','APPROVAL_REJECT','NOTIFICATION_VIEW','AUDIT_VIEW'],
  EMPLOYEE: ['DASHBOARD_VIEW','TRANSACTION_VIEW','TRANSACTION_CREATE','TRANSACTION_UPDATE','ANOMALY_VIEW','FORECAST_VIEW','BUDGET_VIEW','ASSISTANT_USE','NOTIFICATION_VIEW'],
  ACCOUNTANT: ['DASHBOARD_VIEW','TRANSACTION_VIEW','TRANSACTION_CREATE','TRANSACTION_UPDATE','INVOICE_VIEW','INVOICE_UPLOAD','INVOICE_PROCESS','ANOMALY_VIEW','FORECAST_VIEW','BUDGET_VIEW','ASSISTANT_USE','NOTIFICATION_VIEW'],
  CFO: ['DASHBOARD_VIEW','TRANSACTION_VIEW','INVOICE_VIEW','INVOICE_APPROVE','INVOICE_REJECT','VENDOR_VIEW','ANOMALY_VIEW','FORECAST_VIEW','BUDGET_VIEW','RISK_VIEW','ASSISTANT_USE','APPROVAL_VIEW','NOTIFICATION_VIEW','AUDIT_VIEW'],
  AUDITOR: ['DASHBOARD_VIEW','TRANSACTION_VIEW','INVOICE_VIEW','VENDOR_VIEW','ANOMALY_VIEW','FORECAST_VIEW','BUDGET_VIEW','RISK_VIEW','ASSISTANT_USE','APPROVAL_VIEW','NOTIFICATION_VIEW','AUDIT_VIEW'],
};

export const ROLE_ALIASES = { ACCOUNTANT: 'EMPLOYEE', AUDITOR: 'CFO', ADMIN: 'SYSTEM_ADMIN' };

export function hasPermission(user, permission) {
  const role = user?.canonical_role || ROLE_ALIASES[user?.role] || user?.role;
  const granted = user?.permissions || PERMISSIONS[role] || [];
  return granted.includes('*') || granted.includes(permission);
}
