import React, { useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import api from '../services/api';
import DataTable from '../components/DataTable';
import Loading from '../components/Loading';
import PageHeader from '../components/PageHeader';
import RiskBadge from '../components/RiskBadge';
import useAuth from '../hooks/useAuth';

const empty = { date: new Date().toISOString().slice(0, 10), amount: '', transaction_type: 'EXPENSE', category: '', description: '', department: '', currency: 'INR', vendor_id: '', vendor_name: '', payment_method: 'Bank transfer', status: 'COMPLETED' };

export default function Transactions() {
  const { user } = useAuth();
  const [rows, setRows] = useState(null); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  const load = () => api.get('/transactions', { params: { search, page, page_size: 25 } }).then((response) => { setRows(response.data.items || response.data); setTotal(response.data.total || response.data.length); }).catch((e) => setError(e.response?.data?.detail || e.message));
  useEffect(() => { load(); }, [search, page]);
  const change = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  const save = async () => { try { const payload = { ...form, amount: Number(form.amount) }; if (editing) await api.put(`/transactions/${editing}`, payload); else await api.post('/transactions', payload); setOpen(false); setEditing(null); setForm(empty); load(); } catch (e) { setError(e.response?.data?.detail || 'Could not save transaction'); } };
  const edit = (row) => { setEditing(row.transaction_id); setForm({ ...empty, ...row }); setOpen(true); };
  const remove = async (id) => { if (!window.confirm('Delete this transaction?')) return; try { await api.delete(`/transactions/${id}`); load(); } catch (e) { setError(e.response?.data?.detail || 'Could not delete transaction'); } };
  const importFile = async (event) => { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); try { await api.post('/transactions/import', data, { headers: { 'Content-Type': 'multipart/form-data' } }); load(); } catch (e) { setError(e.response?.data?.detail || 'Could not import file'); } event.target.value = ''; };
  const columns = [['transaction_id', 'ID'], ['date', 'Date'], ['department', 'Department'], ['category', 'Category'], ['amount', 'Amount'], ['currency', 'Currency'], ['transaction_type', 'Type'], ['status', 'Status'], ['risk_level', 'Risk', (v) => <RiskBadge level={v} />], ['transaction_id', 'Actions', (v, row) => <Stack direction="row"><Button size="small" onClick={() => edit(row)}>Edit</Button><Button color="error" size="small" onClick={() => remove(v)}>Delete</Button></Stack>]];
  return <><PageHeader title="Transactions" description="Create, import, review, and manage live financial records." /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ mb: 2 }}><Button variant="contained" onClick={() => { setEditing(null); setForm(empty); setOpen(true); }}>Add transaction</Button><Button component="label" variant="outlined">Import CSV / Excel<input hidden type="file" accept=".csv,.xlsx,.xls" onChange={importFile} /></Button><TextField size="small" label="Search" value={search} onChange={(e) => { setPage(1); setSearch(e.target.value); }} /><Typography variant="caption" sx={{ alignSelf: 'center' }}>Visible department: {user?.department || 'All'}</Typography></Stack><Alert severity="info" sx={{ mb: 2 }}>Import columns: date, amount, transaction_type, category. Optional: description, vendor_id, vendor_name, account, payment_method, currency, status, department.</Alert><Alert severity="error" sx={{ display: error ? 'flex' : 'none', mb: 2 }}>{error}</Alert>{!rows ? <Loading /> : <><DataTable rows={rows} columns={columns} /><Stack direction="row" justifyContent="space-between" sx={{ mt: 2 }}><Button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</Button><Typography>Page {page} ({total} total)</Typography><Button disabled={page * 25 >= total} onClick={() => setPage(page + 1)}>Next</Button></Stack></>}<Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Edit transaction' : 'Add transaction'}</DialogTitle><DialogContent sx={{ display: 'grid', gap: 2, pt: '16px !important' }}><TextField type="date" label="Date" value={form.date} onChange={change('date')} InputLabelProps={{ shrink: true }} /><TextField type="number" label="Amount" value={form.amount} onChange={change('amount')} /><TextField select label="Type" value={form.transaction_type} onChange={change('transaction_type')}><MenuItem value="EXPENSE">Expense</MenuItem><MenuItem value="INCOME">Income</MenuItem></TextField><TextField label="Category" value={form.category} onChange={change('category')} required /><TextField label="Currency" value={form.currency} onChange={change('currency')} /><TextField label="Vendor ID" value={form.vendor_id} onChange={change('vendor_id')} /><TextField label="Vendor name" value={form.vendor_name} onChange={change('vendor_name')} /><TextField label="Payment method" value={form.payment_method} onChange={change('payment_method')} /><TextField label="Description" value={form.description} onChange={change('description')} /><TextField label="Department" value={form.department || user?.department || ''} onChange={change('department')} disabled={!['ADMIN', 'FINANCE_MANAGER'].includes(user?.role)} /></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={!form.amount || !form.category}>Save</Button></DialogActions></Dialog></>;
}
